easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Basket
#        - App\Entity\CartItem
        Category:
            class: App\Entity\Category
        Product:
            class: App\Entity\Product
            form:
                 fields:
                    - lib
                    - price
                    - description
                    - { property: 'imageFile', type: 'vich_image' }

