easy_admin:
    entities:
#        # List the entity class name you want to manage
        Basket:
            class: App\Entity\Basket

        CartItem:
            class: App\Entity\CartItem

        Category:
            class: App\Entity\Category
            form:
                 fields:
                    - lib
                    - { property: 'products'}
        Product:
            class: App\Entity\Product
            form:
                 fields:
                    - lib
                    - price
                    - description
                    - { property: 'imageFile', type: 'vich_image'}
                    - category
